name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "arkadswealth-ebdeploymentbucket-zarf8g2p2r90"
  EB_APPLICATION_NAME       : "ArkadsWealthApplication"
  EB_ENVIRONMENT_NAME       : "ArkadsWealthApplication-primary-env"
  DEPLOY_PACKAGE_NAME       : "arkads-wealth-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
    build_application:
       runs-on: ubuntu-latest       
       steps:
         - name: Git clone repository
           uses: actions/checkout@v2
         - name: Set up Python virtual environment
           uses: actions/setup-python@v2
           with:
             python-version: '3.6'
             architecture: 'x64'
