name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "cloudformation1-ebdeploymentbucket-170cif75xotu5"
  EB_APPLICATION_NAME       : "ArkadsWealth"
  EB_ENVIRONMENT_NAME       : "ArkadsWealth-env"
  DEPLOY_PACKAGE_NAME       : "Arkads-Wealth-BGU-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
    build_application:
       runs-on: ubuntu-latest       
       steps:
         - name: Git clone repository
           uses: actions/checkout@v2
         - name: Set up Python virtual environment
           uses: actions/setup-python@v2
           with:
             python-version: '3.6'
             architecture: 'x64'
         - name: Install dependencies
           run: |
             python3 -m venv python
             source python/bin/activate
             pip3 install -r requirements.txt
             deactivate
         - name: Create ZIP deployment package
           run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*
           
         - name: Configure  AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region           : ${{ us-east-2 }}

         - name: Copy deployment package to S3 bucket
           run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
           
    deploy_application:
       runs-on: ubuntu-latest
       needs: [build_application]
       
       steps:
         - name: Configure AWS Credentils
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region           : ${{ us-east-1 }}
         
         - name: Create new Elastic Beanstalk application version
           run : |
            aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
            --version-label "Ver-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"
         - name: Deploy new application version
           run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"
